# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: initial_setup  
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: .azure-pipelines/steps/install-nodejs.yml
    - template: .azure-pipelines/steps/install-dependencies-from-cache.yml
    - powershell: echo "##vso[task.setvariable variable=COMMANDS;isOutput=true]$(node ./tools/scripts/calculate-commands.js)"
      name: setCommands
    - script: echo $(setCommands.COMMANDS)
      name: echovar

  - job: lint1
    dependsOn: initial_setup
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      COMMANDS: $[ dependencies.init_setup.outputs['setCommands.COMMANDS'] ]
    steps:
    - template: .azure-pipelines/steps/install-nodejs.yml
    - template: .azure-pipelines/steps/install-dependencies-from-cache.yml
    - script: node ./tools/scripts/run-commands.js lint1 $(COMMANDS)


